### ISSUE TITLE
wrong port match

### ISSUE THREAD

**Issue by filefox** [For-ACGN/fast-scanner#1]
I found the match bug in sync.go line 150-151 and 180-181 :

`				if uint16(tcp.DstPort) == binary.BigEndian.Uint16(hash[:2]) &&
					tcp.Ack-1 == binary.BigEndian.Uint32(hash[2:6]) && tcp.SYN && tcp.ACK {`

the open port must recvice tcp.SYN and tcp.ACK

**Comment by For-ACGN** [comment]
非常感谢，我已经解决了这个bug，可能当时连接测试目标的非开放端口时目标不会主动返回RST ACK，所以没能测出这个严重的bug。

Thank you! I've fix this bug.

**Comment by filefox** [comment]
大佬是国人啊，害我用蹩脚的英文在这发issue

**Comment by For-ACGN** [comment]
我一只菜鸟而已哈哈哈。 我查了下你的名字，直接能在Freebuf上搜到，而且注册时间和Github的注册时间非常接近，所以你应该也是国人。其实你看一下我的另一个项目P.B.NET的Readme你就知道我也是国人了。

**Comment by filefox** [comment]
最近在用你这个工具，想接到脚本里面去，目前测试很稳定了，还碰到一个gopacket的坑，查了好久，官方还没修，最后在github的issue上看到有大佬修了，刚修没多久。出现方式比较奇葩，高并发下pcap的cgo会报panic，导致进程直接挂掉。
https://github.com/google/gopacket/issues/763

**Comment by For-ACGN** [comment]
我这个的话可以控制sender的数量，也有可能是我用的老版本的gopacket。
不推荐同时开大量Scanner，内核压力大的。

我这边有一个问题就是 _ = handle.SetBPFFilter("tcp[13] = 0x12")
只能抓IPv4的TCP数据包 IPv6的却没有，用Wireshark设置BPF也抓不到

你发的这个问题我看了下，那个示例代码有问题， 首先在for循环里面跑defer()，文件根本不会被关闭(泄露)，然后linux默认每个进程只能同时打开1024个文件(可以改内核参数)。
